# Generated by Django 5.1.2 on 2025-04-28 16:15

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hb', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.EmailField(max_length=50, unique=True)),
                ('card', models.ForeignKey(default=myapp.models.get_default_card, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='myapp.card')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('card', models.ForeignKey(default=myapp.models.get_default_card, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.card')),
                ('ema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ema')),
            ],
        ),
    ]
